// Class automatically generated by Dev-C++ New Class wizard

#include <protocol/handlers/DistanceSensorBoardPacketHandler.h> // class's header file
#include <protocol/packets/DistanceSensorPacket.h>
#include <math.h>

namespace protocol {
namespace handlers {

// class constructor
DistanceSensorBoardPacketHandler::DistanceSensorBoardPacketHandler(PacketServer * ps, char groupid, char boardid)
{
	this->groupid = groupid;
	this->boardid = boardid;
	this->ps = ps;
	this->dsValue[0] = 0;
	this->dsValue[1] = 0;
	this->dsValue[2] = 0;
	this->dsValue[3] = 0;
	this->dsValue[4] = 0;
}

// class destructor
DistanceSensorBoardPacketHandler::~DistanceSensorBoardPacketHandler()
{
	// insert your code here
}

void DistanceSensorBoardPacketHandler::handlePacket(Packet * p){
	packets::DistanceSensorPacket * dsp = new packets::DistanceSensorPacket(groupid,boardid);
	dsp->analysePacket(p);
	
	if ( dsp->getCommand() == CMD_GET_VALUE ){
		short * value = dsp->getSensorValues();
		// TODO convert from short to double
		// Lock Mutex
		#ifdef LINUX
		this->dsValueMutex->enterMutex();
		#endif
		
		this->dsValue[0] = value[0];
		this->dsValue[1] = value[1];
		this->dsValue[2] = value[2];
		this->dsValue[3] = value[3];
		this->dsValue[4] = value[4];
		
		// Release Mutex
		#ifdef LINUX
		this->dsValueMutex->leaveMutex();
		#endif
	}
}

void DistanceSensorBoardPacketHandler::enable(int dsId){
	packets::DistanceSensorPacket * p = new packets::DistanceSensorPacket(groupid,boardid);
	// TODO convert from double to char
	p->on(dsId);
	p->prepareToSend();
	this->ps->sendPacket(p);
}

void DistanceSensorBoardPacketHandler::disable(int dsId){
	packets::DistanceSensorPacket * p = new packets::DistanceSensorPacket(groupid,boardid);
	// TODO convert from double to char
	p->off(dsId);
	p->prepareToSend();
	this->ps->sendPacket(p);
}

int DistanceSensorBoardPacketHandler::getValue(int dsId){
	// TODO Put timestamps to prevent flooding
   	packets::DistanceSensorPacket * p = new packets::DistanceSensorPacket(groupid,boardid);
	p->getValue((char)0x0000003F);
	p->prepareToSend();
	this->ps->sendPacket(p);
	
	// Lock Mutex
	#ifdef LINUX
	this->dsValueMutex->enterMutex();
	#endif

	int value = this->dsValue[dsId];

	// Release Mutex
	#ifdef LINUX
	this->dsValueMutex->leaveMutex();
	#endif
	return value;
}

int DistanceSensorBoardPacketHandler::getOneValue(int dsId){
	// TODO Put timestamps to prevent flooding
   	packets::DistanceSensorPacket * p = new packets::DistanceSensorPacket(groupid,boardid);
	p->getOneValue((char)0x0000003F);
	p->prepareToSend();
	this->ps->sendPacket(p);
	
	// Lock Mutex
	#ifdef LINUX
	this->dsValueMutex->enterMutex();
	#endif

	int value = this->dsValue[dsId];

	// Release Mutex
	#ifdef LINUX
	this->dsValueMutex->leaveMutex();
	#endif
	return value;
}


void DistanceSensorBoardPacketHandler::setMask(int dsId){
	packets::DistanceSensorPacket * p = new packets::DistanceSensorPacket(groupid,boardid);
	p->setMask(dsId);
	p->prepareToSend();
	this->ps->sendPacket(p);
	
}
		
int DistanceSensorBoardPacketHandler::getMask(){
	packets::DistanceSensorPacket * p = new packets::DistanceSensorPacket(groupid,boardid);
	p->getMask();
	p->prepareToSend();
	this->ps->sendPacket(p);
	
	// Lock Mutex
	#ifdef LINUX
	this->dsMaskMutex->enterMutex();
	#endif
	
	int mask=this->dsMask;
	
	// Release Mutex
	#ifdef LINUX
	this->dsValueMutex->leaveMutex();
	#endif
	return mask;

}

}
}

