// Class automatically generated by Dev-C++ New Class wizard

#ifndef DISTANCESENSORBOARDPACKETHANDLER_H
#define DISTANCESENSORBOARDPACKETHANDLER_H

#include <BoardPacketHandler.h> // inheriting class's header file
#include <Packet.h>
#include <PacketServer.h>

namespace handlers {

/**
 * No description
 */
class DistanceSensorBoardPacketHandler : public BoardPacketHandler
{
	public:
		// class constructor
		DistanceSensorBoardPacketHandler(PacketServer * ps, char groupid, char boardid);
		// class destructor
		~DistanceSensorBoardPacketHandler();
		
		void handlePacket(Packet * p);
		
		void enable(int dsId);

		void disable(int dsId);
		
		double getValue(int dsId);
		
	private:
		char groupid;
		char boardid;
		PacketServer * ps;
		
		double dsValue [5];
};

}

#endif // DISTANCESENSORBOARDPACKETHANDLER_CPP
