// Class automatically generated by Dev-C++ New Class wizard

#ifndef TRASHBINBOARDPACKETHANDLER_H
#define TRASHBINBOARDPACKETHANDLER_H

#include <BoardPacketHandler.h> // inheriting class's header file
#include <Packet.h>
#include <PacketServer.h>

namespace handlers {

/**
 * No description
 */
class TrashBinBoardPacketHandler : public BoardPacketHandler
{
	public:
		// class constructor
		TrashBinBoardPacketHandler(PacketServer * ps, char groupid, char boardid);
		// class destructor
		~TrashBinBoardPacketHandler();
		
		void handlePacket(Packet * p);
		
		double getValue();

		bool isFull();

		void setFullBias(double bias);
		
	private:
		char groupid;
		char boardid;
		PacketServer * ps;
		
		double currentValue;
		bool full;
};

}

#endif // TRASHBINBOARDPACKETHANDLER_CPP
