// Class automatically generated by Dev-C++ New Class wizard

#include <protocol/handlers/DistanceSensorBoardPacketHandler.h> // class's header file
#include <protocol/packets/DistanceSensorPacket.h>
#include <math.h>

namespace protocol {
namespace handlers {

// class constructor
DistanceSensorBoardPacketHandler::DistanceSensorBoardPacketHandler(PacketServer * ps, char groupid, char boardid)
{
	this->groupid = groupid;
	this->boardid = boardid;
	this->ps = ps;
	this->dsValue[0] = 0;
	this->dsValue[1] = 0;
	this->dsValue[2] = 0;
	this->dsValue[3] = 0;
	this->dsValue[4] = 0;
}

// class destructor
DistanceSensorBoardPacketHandler::~DistanceSensorBoardPacketHandler()
{
	// insert your code here
}

void DistanceSensorBoardPacketHandler::handlePacket(Packet * p){
	packets::DistanceSensorPacket * dsp = new packets::DistanceSensorPacket(groupid,boardid);
	dsp->analysePacket(p);
	
	if ( dsp->getCommand() == CMD_GET_ALL_VALUES ){
		short * value = dsp->getSensorValues();
		// TODO convert from short to double
		// Lock Mutex
		this->dsValue[0] = value[0];
		this->dsValue[1] = value[1];
		this->dsValue[2] = value[2];
		this->dsValue[3] = value[3];
		this->dsValue[4] = value[4];
		// Release Mutex
	}
}

void DistanceSensorBoardPacketHandler::enable(int dsId){
	packets::DistanceSensorPacket * p = new packets::DistanceSensorPacket(groupid,boardid);
	// TODO convert from double to char
	p->enableSensor(dsId);
	p->prepareToSend();
	this->ps->sendPacket(p);
}

void DistanceSensorBoardPacketHandler::disable(int dsId){
	packets::DistanceSensorPacket * p = new packets::DistanceSensorPacket(groupid,boardid);
	// TODO convert from double to char
	p->disableSensor(dsId);
	p->prepareToSend();
	this->ps->sendPacket(p);
}

int DistanceSensorBoardPacketHandler::getValue(int dsId){
	// TODO Put timestamps to prevent flooding
   	packets::DistanceSensorPacket * p = new packets::DistanceSensorPacket(groupid,boardid);
	p->getSensor();
	p->prepareToSend();
	this->ps->sendPacket(p);
	return this->dsValue[dsId];
}

}
}

