// Class automatically generated by Dev-C++ New Class wizard

#ifndef SERVOBOARDPACKETHANDLER_H
#define SERVOBOARDPACKETHANDLER_H

#include <protocol/BoardPacketHandler.h> // inheriting class's header file
#include <protocol/Packet.h>
#include <protocol/PacketServer.h>

namespace protocol {
namespace handlers {

/**
 * No description
 */
class ServoBoardPacketHandler : public protocol::BoardPacketHandler
{
	public:
		// class constructor
		ServoBoardPacketHandler(PacketServer * ps, char groupid, char boardid);
		// class destructor
		~ServoBoardPacketHandler();
		
		void handlePacket(Packet * p);
		
		void setPosition(int servoId, double position);

		void setSpeed(int servoId, double speed);
		
		double getPosition(int servoId);
		
		void setForce(int servoId, double force);
	private:
		char groupid;
		char boardid;
		PacketServer * ps;
		
		double positionValue [5];
};

}
}


#endif // SERVOBOARDPACKETHANDLER_CPP
