// Class automatically generated by Dev-C++ New Class wizard

#ifndef TRASHBINBOARDPACKETHANDLER_H
#define TRASHBINBOARDPACKETHANDLER_H

#include <protocol/BoardPacketHandler.h> // inheriting class's header file
#include <protocol/Packet.h>
#include <protocol/PacketServer.h>

namespace protocol {
namespace handlers {

/**
 * No description
 */
class TrashBinBoardPacketHandler : public protocol::BoardPacketHandler
{
	public:
		// class constructor
		TrashBinBoardPacketHandler(PacketServer * ps, char groupid, char boardid);
		// class destructor
		~TrashBinBoardPacketHandler();
		
		void handlePacket(Packet * p);
		
		int getValue();

		bool isFull();

		void setFullBias(double bias);
		
	private:
		char groupid;
		char boardid;
		PacketServer * ps;
		
		int currentValue;
		bool full;
};

}
}


#endif // TRASHBINBOARDPACKETHANDLER_CPP
