// Class automatically generated by Dev-C++ New Class wizard

#include <protocol/handlers/TrashBinBoardPacketHandler.h> // class's header file
#include <protocol/packets/TrashBinPacket.h>
#include <math.h>

namespace protocol {
namespace handlers {

// class constructor
TrashBinBoardPacketHandler::TrashBinBoardPacketHandler(PacketServer * ps, char groupid, char boardid)
{
	this->groupid = groupid;
	this->boardid = boardid;
	this->ps = ps;
	this->currentValue = 0;
	this->full = false;

#ifdef LINUX
	this->currentValueMutex = new Mutex();
	this->fullMutex = new Mutex();
#endif
}

// class destructor
TrashBinBoardPacketHandler::~TrashBinBoardPacketHandler()
{
	// insert your code here
}

void TrashBinBoardPacketHandler::handlePacket(Packet * p){
	packets::TrashBinPacket * tbp = new packets::TrashBinPacket(groupid,boardid);
	tbp->analysePacket(p);
	
	if ( tbp->getCommand() == CMD_TRASHBIN_VALUE ){
		short value = tbp->getTrashBinValue();
		// TODO convert from short to int
		// Lock Mutex
		this->currentValue = value;
		// Release Mutex
	}
	if ( tbp->getCommand() == CMD_FULL_TRASHBIN_ALARM ){
		// Lock Mutex
		this->full = true;
		// Release Mutex
	}
}

int TrashBinBoardPacketHandler::getValue(){
 	packets::TrashBinPacket * p = new packets::TrashBinPacket(groupid,boardid);
	p->senseTrashBin();
	p->prepareToSend();
	this->ps->sendPacket(p);
	return this->currentValue;
}

bool TrashBinBoardPacketHandler::isFull(){
	// Lock mutex
	bool full = this->full;
	// Release mutex
	return full;
}

void TrashBinBoardPacketHandler::setFullBias(double bias){
	packets::TrashBinPacket * p = new packets::TrashBinPacket(groupid,boardid);
	// TODO convert from double to char
	p->setTrashBinFullThreshold(bias);
	p->prepareToSend();
	this->ps->sendPacket(p);
}

}
}

