// Class automatically generated by Dev-C++ New Class wizard

#include <utils/ArenaGridSlot.h> // class's header file
#include <string.h>

namespace utils {

// class constructor
ArenaGridSlot::ArenaGridSlot(double x, double z, int i, int j, time_t timestamp)
{
	this->x = x;
	this->z = z;
	this->i = i;
	this->j = j;
	this->timestamp = timestamp;
}

ArenaGridSlot::ArenaGridSlot(utils::ArenaGridSlot * ags, int dir){
	this->x = ags->getX();
	this->z = ags->getZ();
	this->timestamp = ags->getTimeStamp();
	this->dir = dir;
}

time_t ArenaGridSlot::getTimeStamp(){
	return this->timestamp;
}

time_t ArenaGridSlot::setTimeStamp(){
	return this->setTimeStamp(time(NULL));
}

time_t ArenaGridSlot::setTimeStamp(time_t timestamp){
	time_t last = this->timestamp;
	this->timestamp = timestamp;
	return last;
}

double ArenaGridSlot::getX(){
	return this->x;
}

double ArenaGridSlot::getZ(){
	return this->z;
}

int ArenaGridSlot::getI(){
	return this->i;
}

int ArenaGridSlot::getJ(){
	return this->j;
}

int ArenaGridSlot::getDir(){
	return this->dir;
}

// class destructor
ArenaGridSlot::~ArenaGridSlot()
{
	// insert your code here
}

}
