// Class automatically generated by Dev-C++ New Class wizard

#include <utils/ArenaGridSlot.h> // class's header file

namespace utils {

// class constructor
ArenaGridSlot::ArenaGridSlot(double x, double z, time_t timestamp)
{
	this->x = x;
	this->z = z;
	this->timestamp = timestamp;
}

time_t ArenaGridSlot::getTimeStamp(){
	return this->timestamp;
}

void ArenaGridSlot::setTimeStamp(){
	// TODO!!! Set actual time
	this->setTimeStamp(time(NULL));
}

void ArenaGridSlot::setTimeStamp(time_t timestamp){
	this->timestamp = timestamp;
}

double ArenaGridSlot::getX(){
	return this->x;
}

double ArenaGridSlot::getZ(){
	return this->z;
}

// class destructor
ArenaGridSlot::~ArenaGridSlot()
{
	// insert your code here
}

}
