// Class automatically generated by Dev-C++ New Class wizard

#ifndef utils_MyAngle_h
#define utils_MyAngle_h

#define PI 3.1415926535897932384626433832795
#define HALF_PI (PI/2)
#define THREE_HALF_PI (3*HALF_PI)
#define TWO_PI (2*PI)

namespace utils {

/**
 * No description
 */
class MyAngle
{
	public:
		// class constructor
		MyAngle(double value);
		// class destructor
		~MyAngle();
		
		double getNormalizedValue();
		double differenceTo(MyAngle * ma);
		double getValue();
		static MyAngle * zeroAngle();
		static MyAngle * halfPiAngle();
		static MyAngle * piAngle();
		static MyAngle * threeHalvesPiAngle();
	private:
		double getNormalizedValue(double angle);
		double value;

};

}
#endif // utils_MyAngle_h
