// Class automatically generated by Dev-C++ New Class wizard

#include <utils/MyPoint.h> // class's header file

namespace utils {

// class constructor
MyPoint::MyPoint(double x, double y)
{
	this->x = x;
	this->y = y;
}

// class destructor
MyPoint::~MyPoint()
{
	// insert your code here
}

double MyPoint::getX(){
	return this->x;
}
double MyPoint::getY(){
	return this->y;
}

}
