// Class automatically generated by Dev-C++ New Class wizard

#include <utils/OdometryInfo.h> // class's header file

namespace utils{

// class constructor
OdometryInfo::OdometryInfo()
{
	// insert your code here
}

// class destructor
OdometryInfo::~OdometryInfo()
{
	// insert your code here
}

double OdometryInfo::getOrientation(){
	return 0.0;
}

}
