// Class automatically generated by Dev-C++ New Class wizard

#include <utils/OdometryInfo.h> // class's header file
#include <math.h>

namespace utils{

// class constructor
OdometryInfo::OdometryInfo(robotapi::IDifferentialWheels * wheels, double distanceBetweenWheels, double wheelRadius, double encoderResolution, double initialX, double initialY, double initialTheta)
{
	this->distanceBetweenWheels = distanceBetweenWheels;
	this->wheelRadius = wheelRadius;
	this->encoderResolution = encoderResolution;
	this->wheels = wheels;
	this->lastPosition = new utils::MyPoint(initialX,initialY);
	this->lastAngle = new utils::MyAngle(initialTheta);
	this->lastLeftEncoder = this->wheels->getLeftEncoder();
	this->lastRightEncoder = this->wheels->getRightEncoder();
}

// class destructor
OdometryInfo::~OdometryInfo()
{
	// insert your code here
}

void OdometryInfo::computeOdometry() {
	double l = this->wheels->getLeftEncoder();
	double r = this->wheels->getRightEncoder();
	double dl = (l - this->lastLeftEncoder ) * this->wheelRadius / this->encoderResolution ; // distance covered by left wheel in meter
	double dr = (r - this->lastRightEncoder ) * this->wheelRadius / this->encoderResolution ; // distance covered by right wheel in meter

	this->computePosition(dl, dr);

	this->lastLeftEncoder = l;
	this->lastRightEncoder = r;

	//printf("estimated distance covered by left wheel: %g m.\n",dl);
	//printf("estimated distance covered by right wheel: %g m.\n",dr);
	//printf("estimated change of orientation: %g rad.\n",da);
}

void OdometryInfo::computePosition(double ldist, double rdist){
	double lc = 0;
	lc = (ldist+rdist)/2.0;

	utils::MyAngle * dtita = new utils::MyAngle((rdist-ldist)/this->distanceBetweenWheels); // delta orientation
	this->lastAngle->add(dtita);
	delete dtita;

	this->lastPosition->add(lc * cos(this->lastAngle->getNormalizedValue()), lc * sin(this->lastAngle->getNormalizedValue()));
	return;
}

double OdometryInfo::getOrientation(){
	return this->lastAngle->getNormalizedValue();
}

utils::MyPoint * OdometryInfo::getPosition(){
	return this->lastPosition;
}

}
