// Class automatically generated by Dev-C++ New Class wizard

#ifndef utils_OdometryInfo_h
#define utils_OdometryInfo_h

namespace utils{

/**
 * No description
 */
class OdometryInfo
{
	public:
		// class constructor
		OdometryInfo();
		// class destructor
		~OdometryInfo();
		
		double getOrientation();
};

}

#endif // ODOMETRYINFO_H
