// Class automatically generated by Dev-C++ New Class wizard

#ifndef PACKETSERVER_H
#define PACKETSERVER_H

#include <queue>
#include <list>
#include <map>
#include <protocol/Packet.h>
#include <protocol/BoardPacketHandler.h>

namespace protocol {

/**
 * No description
 */
class PacketServer
{
	public:
		// class constructor
		PacketServer();
		// class destructor
		~PacketServer();
		
		void sendPacket(Packet * p);
		void run(void);
	private:
		void sendAPacket(Packet * p);
		std::queue<Packet *> toSend;
		std::list<Packet *> waitingForResponse;
		std::map<char, std::map<char, BoardPacketHandler *> > handlers;
};

}

#endif // PACKETSERVER_H
