#include "GarbageCleaner.h"
#include <behaviours/AvoidObstacle.h>
#include <behaviours/CollectGarbage.h>
#include <behaviours/FindLine.h>
#include <behaviours/FocusGarbage.h>
#include <behaviours/GoToBase.h>
#include <behaviours/GoToDisposal.h>
#include <behaviours/Recharge.h>
#include <behaviours/UnloadGarbage.h>
#include <behaviours/Wander.h>
#include <iostream>

GarbageCleaner::GarbageCleaner(robotapi::IRobot & robot) : myIRobot(robot)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DB6 begin
{
	initializeBehaviours();
}
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DB6 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


void GarbageCleaner::initializeBehaviours(){
    behaviours::AbstractBehaviour * w = new behaviours::Wander();
    myAbstractBehaviours.push_back(w);
    w = new behaviours::Wander();
    myAbstractBehaviours.push_back(w);
    w = new behaviours::Wander();
    myAbstractBehaviours.push_back(w);
    w = new behaviours::Wander();
    myAbstractBehaviours.push_back(w);
}

void GarbageCleaner::cleanGarbage()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DBA begin
{
	std::list<behaviours::AbstractBehaviour*>::iterator it;

	std::cout << "mylist contains:";
	for ( it=myAbstractBehaviours.begin() ; it != myAbstractBehaviours.end(); it++ )
		std::cout << "\n" << (*it)->toString();

}
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DBA end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element
