// Class automatically generated by Dev-C++ New Class wizard

#include <protocol/packets/FloorSensorPacket.h> // class's header file

namespace protocol {
namespace packets {

// class constructor
FloorSensorPacket::FloorSensorPacket(char groupid, char boardid) : protocol::packets::DistanceSensorPacket(groupid, boardid)
{
}

// class destructor
FloorSensorPacket::~FloorSensorPacket()
{
	// insert your code here
}

}
}

