// Class automatically generated by Dev-C++ New Class wizard

#include <protocol/packets/UltraSonicSensorPacket.h> // class's header file

namespace protocol {
namespace packets {

// class constructor
UltrasonicSensorPacket::UltrasonicSensorPacket(char groupid, char boardid) : protocol::packets::DistanceSensorPacket(groupid, boardid)
{
}

// class destructor
UltrasonicSensorPacket::~UltrasonicSensorPacket()
{
	// insert your code here
}

}
}

