// Class automatically generated by Dev-C++ New Class wizard

#include "baseprotocol.h" // class's header file

// class constructor
BaseProtocol::BaseProtocol()
{
	// insert your code here
}

// class destructor
BaseProtocol::~BaseProtocol()
{
	// insert your code here
}

void BaseProtocol::setInit(){
	this->setCommand(BP_INIT);
}

void BaseProtocol::setReset(){
   	this->setCommand(BP_RESET);
}

void BaseProtocol::setPing(){
	this->setCommand(BP_PING);
}

void BaseProtocol::setError(){
	this->setCommand(BP_ERROR);
}

bool BaseProtocol::isError(){
	return this->getCommand() == BP_ERROR;
}

char BaseProtocol::getErrorCode(){
	char * data = this->getData();
	return data[0];
}

std::string BaseProtocol::getErrorString(){
   	char * data = this->getData();
	char length = this->getDataLength();
	char i;
	std::string * out = new std::string();

	for ( i = 1 ; i < length ; i++ )
		out->append(1,data[i]);
	return *out;
}
