// Class automatically generated by Dev-C++ New Class wizard

#include "BoardPacket.h" // class's header file

// class constructor
BoardPacket::BoardPacket(char groupid, char boardid) : GroupPacket(groupid)
{
	this->boardid = boardid;
	// insert your code here
}

// class destructor
BoardPacket::~BoardPacket()
{
	// insert your code here
}

void BoardPacket::prepareToSend(){
	GroupPacket::prepareToSend();
	this->setDestinationId(this->boardid);
}
