// Class automatically generated by Dev-C++ New Class wizard

#ifndef DCMOTORBOARDPACKETHANDLER_H
#define DCMOTORBOARDPACKETHANDLER_H

#include "BoardPacketHandler.h" // inheriting class's header file
#include "Packet.h"
#include "PacketServer.h"

/**
 * No description
 */
class DCMotorBoardPacketHandler : public BoardPacketHandler
{
	public:
		// class constructor
		DCMotorBoardPacketHandler(PacketServer * ps, char groupid, char boardid);
		// class destructor
		~DCMotorBoardPacketHandler();
		
		void handlePacket(Packet * p);
		
		void setSpeed(double value);

		void enableEncoder();

		double getEncoder();

		void moveWheel(double value);

		void moveWheel(double counts, double speed);

		double getMotorConsumption();

		double getAverageConsumption();
	private:
		char groupid;
		char boardid;
		PacketServer * ps;
};

#endif // DCMOTORBOARDPACKETHANDLER_CPP
