// Class automatically generated by Dev-C++ New Class wizard

#include "dcmotorpacket.h" // class's header file

// class constructor
DCMotorPacket::DCMotorPacket() : GroupPacket(DCMOTORPACKET_ID)
{
	// insert your code here
	printf("%d\n",this->groupid);
}

// class destructor
DCMotorPacket::~DCMotorPacket()
{
	// insert your code here
}
