// Class automatically generated by Dev-C++ New Class wizard

#include "DistanceSensorPacket.h" // class's header file

// class constructor
DistanceSensorPacket::DistanceSensorPacket(char groupid, char boardid) : BoardPacket(groupid, boardid)
{
}

// class destructor
DistanceSensorPacket::~DistanceSensorPacket()
{
	// insert your code here
}

void DistanceSensorPacket::enableSensor(char sensorId){
	this->addData(sensorId);
	this->setCommand(CMD_ENABLE);
}

void DistanceSensorPacket::disableSensor(char sensorId){
	this->addData(sensorId);
	this->setCommand(CMD_DISABLE);
}

void DistanceSensorPacket::setAllSensors(char sensorIds){
	this->addData(sensorIds);
	this->setCommand(CMD_SET_ALL);
}

void DistanceSensorPacket::getSensor(char sensorId){
	this->addData(sensorId);
	this->setCommand(CMD_GET_VALUE);
}

void DistanceSensorPacket::getSensor(){
	this->setCommand(CMD_GET_ALL_VALUES);
}

void DistanceSensorPacket::getShotSensor(char sensorId){
	this->addData(sensorId);
	this->setCommand(CMD_GET_SHOT_VALUE);
}

void DistanceSensorPacket::getShotSensor(){
	this->setCommand(CMD_GET_SHOT_ALL_VALUES);
}






short DistanceSensorPacket::getSensorValue(){
	return this->getShortData();
}

short * DistanceSensorPacket::getSensorValues(){
	// TODO
	/*
	int dataLength = this->getDataLength();
	char * data = this->getData();
	*/
	return NULL;
}

short DistanceSensorPacket::getShotSensorValue(){
	return this->getSensorValue();
}

short * DistanceSensorPacket::getShotSensorValues(){
	return this->getSensorValues();
}
