// Class automatically generated by Dev-C++ New Class wizard

#include "floorsensorpacket.h" // class's header file

// class constructor
FloorSensorPacket::FloorSensorPacket(char groupid, char boardid) : DistanceSensorPacket(groupid, boardid)
{
}

// class destructor
FloorSensorPacket::~FloorSensorPacket()
{
	// insert your code here
}
