// Class automatically generated by Dev-C++ New Class wizard

#ifndef FLOORSENSORPACKET_H
#define FLOORSENSORPACKET_H

#include "DistanceSensorPacket.h" // inheriting class's header file

/**
 * No description
 */
class FloorSensorPacket : public DistanceSensorPacket
{
	public:
		// class constructor
		FloorSensorPacket(char groupid, char boardid);
		// class destructor
		~FloorSensorPacket();

};

#endif // FLOORSENSORPACKET_H
