// Class automatically generated by Dev-C++ New Class wizard

#ifndef GROUPPACKET_H
#define GROUPPACKET_H

#include "packet.h" // inheriting class's header file
#include <string>

#define BP_INIT 0x01
#define BP_RESET 0x02
#define BP_PING 0x03
#define BP_ERROR 0x04
#define ORIGIN_GROUP 0x00
#define ORIGIN_ID 0x00

/**
 * No description
 */
class GroupPacket : public Packet
{
	public:
		// class constructor
		GroupPacket(char groupid);
		// class destructor
		~GroupPacket();
		void setInit();
		void setReset();
		void setPing();
		void setError();
		bool isError();
		char getErrorCode();
		std::string getErrorString();
		void prepareToSend();
		void analysePacket(Packet * p);
	protected:
		char groupid;
};

#endif // GROUPPACKET_H

