// Class automatically generated by Dev-C++ New Class wizard

#ifndef SERVOMOTORPACKET_H
#define SERVOMOTORPACKET_H

#define SERVOMOTORPACKET_ID 0x02
#include "GroupPacket.h" // inheriting class's header file

/**
 * No description
 */
class ServoMotorPacket : public GroupPacket
{
	public:
		// class constructor
		ServoMotorPacket();
		// class destructor
		~ServoMotorPacket();
};

#endif // SERVOMOTORPACKET_H
