// Class automatically generated by Dev-C++ New Class wizard

#ifndef SERVOBOARDPACKETHANDLER_H
#define SERVOBOARDPACKETHANDLER_H

#include "BoardPacketHandler.h" // inheriting class's header file
#include "Packet.h"

/**
 * No description
 */
class ServoBoardPacketHandler : public BoardPacketHandler
{
	public:
		// class constructor
		ServoBoardPacketHandler();
		// class destructor
		~ServoBoardPacketHandler();
		
		void handlePacket(Packet * p);
};

#endif // SERVOBOARDPACKETHANDLER_CPP
