// Class automatically generated by Dev-C++ New Class wizard

#include "servomotorpacket.h" // class's header file

// class constructor
ServoMotorPacket::ServoMotorPacket() : GroupPacket(SERVOMOTORPACKET_ID)
{
	// insert your code here
	printf("%d\n",this->groupid);
}

// class destructor
ServoMotorPacket::~ServoMotorPacket()
{
	// insert your code here
}
