// Class automatically generated by Dev-C++ New Class wizard

#ifndef TRASHBINPACKET_H
#define TRASHBINPACKET_H

#include "GroupPacket.h" // inheriting class's header file

#define TRASHBIN_ID 0x06

#define CMD_TRASHBIN_VALUE 0x40
#define CMD_FULL_TRASHBIN_ALARM 0x41

/**
 * No description
 */
class TrashBinPacket : public GroupPacket
{
	public:
		// class constructor
		TrashBinPacket();
		// class destructor
		~TrashBinPacket();

		void senseTrashBin();
		bool isTrashBinFull();
		
		short getTrashBinValue();
};

#endif // TRASHBINPACKET_H
