// Class automatically generated by Dev-C++ New Class wizard

#ifndef ULTRASONICSENSORPACKET_H
#define ULTRASONICSENSORPACKET_H

#include "DistanceSensorPacket.h" // inheriting class's header file

/**
 * No description
 */
class UltrasonicSensorPacket : public DistanceSensorPacket
{
	public:
		// class constructor
		UltrasonicSensorPacket(char groupid, char boardid);
		// class destructor
		~UltrasonicSensorPacket();

};

#endif // ULTRASONICSENSORPACKET_H
