#include "AbstractBehaviour.h"

namespace behaviours {

void AbstractBehaviour::act()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DCB begin
{
    
}
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DCB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool AbstractBehaviour::isMyAction()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DCD begin
{
    return true;
}
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DCD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace behaviours */
