// Class automatically generated by Dev-C++ New Class wizard

#ifndef FLOORSENSORPACKET_H
#define FLOORSENSORPACKET_H

#include <protocol/packets/DistanceSensorPacket.h> // inheriting class's header file

namespace protocol {
namespace packets {
	
/**
 * No description
 */
class FloorSensorPacket : public protocol::packets::DistanceSensorPacket
{
	public:
		// class constructor
		FloorSensorPacket(char groupid, char boardid);
		// class destructor
		~FloorSensorPacket();

};

}
}

#endif // FLOORSENSORPACKET_H
