// Class automatically generated by Dev-C++ New Class wizard

#ifndef behaviours_PositionInLine_h
#define behaviours_PositionInLine_h

#include <behaviours/AbstractBehaviour.h> // inheriting class's header file
#include "WorldInfo.h"
#include <vector>

namespace behaviours {

/**
 * No description
 */
class PositionInLine : public AbstractBehaviour
{
	public:
		// class constructor
		PositionInLine(WorldInfo * wi, robotapi::IDifferentialWheels * wheels, std::vector<robotapi::IDistanceSensor*> & fss);
		// class destructor
		~PositionInLine();
		
		void sense();

	    void action();

	private:
		std::vector<robotapi::IDistanceSensor*> * fss;
		robotapi::IDifferentialWheels * wheels;
		WorldInfo * wi;
};

}
#endif // POSITIONINLINE_H
