#include "GarbageRecognition.h"

namespace utils {

 {


void GarbageRecognition::setCamera(robotapi::ICamera &camera)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DF2 begin
{
}
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DF2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

bool GarbageRecognition::thereIsGarbage()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DF5 begin
{
    return false;
}
// section -64--88-1-100--1230920c:125cb7ecd6f:-8000:0000000000000DF5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

List<Garbage> GarbageRecognition::getGarbageList()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010C2 begin
{
}
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010C2 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace utils */
