// Class automatically generated by Dev-C++ New Class wizard

#ifndef PACKETSERVER_H
#define PACKETSERVER_H

#include <queue>
#include <list>
#include <map>
#include <protocol/Packet.h>
#include <protocol/BoardPacketHandler.h>


#define SERIAL_PORT "/dev/ttyUSB0"
#define MAX(a,b) (a>b?a:b)
#define PIPE_IN 0
#define PIPE_OUT 1


#ifdef __linux__
#include <cc++/thread.h>
#endif

namespace protocol {

/**
 * No description
 */
#ifdef __linux__
class PacketServer : public ost::Thread {
#else
class PacketServer {
#endif

	public:
		// class constructor
		PacketServer();
		// class destructor
		~PacketServer();
		
		void sendPacket(Packet * p);
		void registerHandler(BoardPacketHandler * bph,int groupid,int boardid);

	private:
		BoardPacketHandler * getHandler(unsigned char groupid,unsigned char boardid);
		bool init();
		void sendAPacket(Packet * p);
		void readNBytes(int fd, char * buff, int nBytes);
		std::queue<Packet *> toSend;
		std::list<Packet *> waitingForResponse;
		std::map<char, std::map<char, BoardPacketHandler *> > handlers;
		BoardPacketHandler * defaultHandler;
		void run(void);

		#ifdef __linux__
		int pipes[2];
		int serfd;
		ost::Mutex toSendMutex;
		#endif
		
};

}

#endif // PACKETSERVER_H
