// Class automatically generated by Dev-C++ New Class wizard

#ifndef ULTRASONICSENSORPACKET_H
#define ULTRASONICSENSORPACKET_H

#include <protocol/packets/DistanceSensorPacket.h> // inheriting class's header file

namespace protocol {
namespace packets {

/**
 * No description
 */
class UltrasonicSensorPacket : public protocol::packets::DistanceSensorPacket
{
	public:
		// class constructor
		UltrasonicSensorPacket(char groupid, char boardid);
		// class destructor
		~UltrasonicSensorPacket();

};

}
}

#endif // ULTRASONICSENSORPACKET_H
