// Class automatically generated by Dev-C++ New Class wizard

#include <utils/ArenaGrid.h> // class's header file
#include <ctime>

namespace utils {

// class constructor
ArenaGrid::ArenaGrid(double arenaMinX, double arenaMinZ, double arenaMaxX, double arenaMaxZ,
					int resolutionX,int resolutionZ)
{
	this->xMin = arenaMinX;
	this->zMin = arenaMinZ;
	this->dx = (arenaMaxX - arenaMinX) / (double)resolutionX;
	this->dz = (arenaMaxZ - arenaMinZ) / (double)resolutionZ;
	
	int maxI = this->getI(arenaMaxX);
	int maxJ = this->getJ(arenaMaxZ);
	
	// TODO!!! CALL TIME!
	time_t timestamp = time(NULL);
	for( int i = 0 ; i < maxI ; i++ ){
		for( int j = 0 ; j < maxJ ; j++ ){
			this->slots[i][j] = new utils::ArenaGridSlot(arenaMinX + i*dx,arenaMinZ + j*dz,timestamp);
		}
	}
}

// class destructor
ArenaGrid::~ArenaGrid()
{
	// insert your code here
}

int ArenaGrid::getI(double x){
    return (x - this->xMin)/this->dx;
}

int ArenaGrid::getJ(double z){
	return (z - this->zMin)/this->dz;
}

utils::ArenaGridSlot * ArenaGrid::getSlotAt(utils::MyPoint * p){
	int i = this->getI(p->getX());
	int j = this->getJ(p->getY());

 	utils::ArenaGridSlot * slot = this->slots[i][j];
	return slot;
}

}
