// Class automatically generated by Dev-C++ New Class wizard

#ifndef utils_ArenaGridSlot_h
#define utils_ArenaGridSlot_h
#include <iostream>
#include <ctime>

namespace utils {

/**
 * No description
 */
class ArenaGridSlot
{
	public:
		// class constructor
		ArenaGridSlot( double x, double z, time_t timestamp);

		ArenaGridSlot( utils::ArenaGridSlot * ags, int dir);

		// class destructor
		~ArenaGridSlot();

		time_t getTimeStamp();
		void setTimeStamp();
		void setTimeStamp(time_t timestamp);
		double getX();
		double getZ();
		int getDir();
	private:
		double x;
		double z;
		time_t timestamp;
		int dir;
};

}
#endif // utils_ArenaGridSlot_h
