// Class automatically generated by Dev-C++ New Class wizard

#include "line.h" // class's header file

namespace utils {

// class constructor
Line::Line()
{
	// insert your code here
}

// class destructor
Line::~Line()
{
	// insert your code here
}

double Line::getOrientation(){
	return 0.0;
}

}
