// Class automatically generated by Dev-C++ New Class wizard

#ifndef utils_Line_h
#define utils_Line_h

namespace utils {

/**
 * No description
 */
class Line
{
	public:
		// class constructor
		Line();
		// class destructor
		~Line();
		
		double getOrientation();
};

}
#endif // utils_Line_h
