// Class automatically generated by Dev-C++ New Class wizard

#include <utils/MyAngle.h> // class's header file
#include <math.h>

namespace utils {

// class constructor
MyAngle::MyAngle(double value)
{
	this->value = value;
}

// class destructor
MyAngle::~MyAngle()
{
	// insert your code here
}

double MyAngle::getNormalizedValue(){
    return this->getNormalizedValue( this->value );
}

double MyAngle::getNormalizedValue(double angle){
	if ( angle >= TWO_PI )
	    return this->getNormalizedValue( angle - TWO_PI );
	if ( angle < 0 )
	    return this->getNormalizedValue( angle + TWO_PI );
	return angle;
}

double MyAngle::differenceTo(MyAngle * ma){
	double nv = this->getNormalizedValue();
	double manv = ma->getNormalizedValue();
	double diff = fabs( nv - manv );
	if ( diff > PI )
	    return TWO_PI - diff;
	return diff;
}

void MyAngle::add(MyAngle * ma){
	double nv = this->getNormalizedValue();
	double manv = ma->getNormalizedValue();
	this->value = this->getNormalizedValue(nv + manv);
}

double MyAngle::getValue(){
	return this->value;
}

}
