#include "Rectangle.h"



int Rectangle::getTopX()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010DF begin
{
    return x;
}
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010DF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Rectangle::getTopY()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010E1 begin
{
    return y;
}
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010E1 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Rectangle::getWidth()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010E3 begin
{
    return width;
}
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010E3 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

int Rectangle::getHeight()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010E5 begin
{
    return height;
}
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010E5 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rectangle::Rectangle(int x,int y,int height,int width)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010E5 begin
{
  this->height=height;
  this->width=width;
  this->x=x;
  this->y=y;
}
