// Class automatically generated by Dev-C++ New Class wizard

#include <packets/BatteryPacket.h> // class's header file

namespace packets {

// class constructor
BatteryPacket::BatteryPacket(char groupid, char boardid) : packets::BoardPacket(groupid,boardid)
{
}

// class destructor
BatteryPacket::~BatteryPacket()
{
	// insert your code here
}

void BatteryPacket::senseBattery(){
	this->setCommand(CMD_BATTERY_VALUE);
}

bool BatteryPacket::isBatteryFull(){
	return this->getCommand() == CMD_FULL_BATTERY_ALARM;
}

void BatteryPacket::setBatteryEmptyThreshold(short value){
	this->setCommand(CMD_BATTERY_EMPTY_VALUE);
	this->addData(value);
}

bool BatteryPacket::isBatteryEmpty(){
	return this->getCommand() == CMD_BATTERY_EMPTY_ALARM;
}

void BatteryPacket::setBatteryFullThreshold(short value){
	this->setCommand(CMD_BATTERY_FULL_VALUE);
	this->addData(value);
}

short BatteryPacket::getBatteryValue(){
	return this->getShortData();
}

}
