// Class automatically generated by Dev-C++ New Class wizard

#include <packets/BoardPacket.h> // class's header file

namespace packets {

// class constructor
BoardPacket::BoardPacket(char groupid, char boardid) : packets::GroupPacket(groupid)
{
	this->boardid = boardid;
	// insert your code here
}

// class destructor
BoardPacket::~BoardPacket()
{
	// insert your code here
}

void BoardPacket::prepareToSend(){
	GroupPacket::prepareToSend();
	this->setDestinationId(this->boardid);
}

}
