// Class automatically generated by Dev-C++ New Class wizard

#ifndef FLOORSENSORPACKET_H
#define FLOORSENSORPACKET_H

#include <packets/DistanceSensorPacket.h> // inheriting class's header file

namespace packets {
	
/**
 * No description
 */
class FloorSensorPacket : public packets::DistanceSensorPacket
{
	public:
		// class constructor
		FloorSensorPacket(char groupid, char boardid);
		// class destructor
		~FloorSensorPacket();

};

}
#endif // FLOORSENSORPACKET_H
