// Class automatically generated by Dev-C++ New Class wizard

#include "BasePacket.h" // class's header file

// class constructor
BasePacket::BasePacket()
{
	// insert your code here
}

// class destructor
BasePacket::~BasePacket()
{
	// insert your code here
}

void BasePacket::setInit(){
	this->setCommand(BP_INIT);
}

void BasePacket::setReset(){
   	this->setCommand(BP_RESET);
}

void BasePacket::setPing(){
	this->setCommand(BP_PING);
}

void BasePacket::setError(){
	this->setCommand(BP_ERROR);
}

bool BasePacket::isError(){
	return this->getCommand() == BP_ERROR;
}

char BasePacket::getErrorCode(){
	char * data = this->getData();
	return data[0];
}

std::string BasePacket::getErrorString(){
   	char * data = this->getData();
	char length = this->getDataLength();
	char i;
	std::string * out = new std::string();

	for ( i = 1 ; i < length ; i++ )
		out->append(1,data[i]);
	return *out;
}
