// Class automatically generated by Dev-C++ New Class wizard

#ifndef BATTERYBOARDPACKETHANDLER_H
#define BATTERYBOARDPACKETHANDLER_H

#include "BoardPacketHandler.h" // inheriting class's header file
#include "Packet.h"
#include "PacketServer.h"

/**
 * No description
 */
class BatteryBoardPacketHandler : public BoardPacketHandler
{
	public:
		// class constructor
		BatteryBoardPacketHandler(PacketServer * ps, char groupid, char boardid);
		// class destructor
		~BatteryBoardPacketHandler();
		
		void handlePacket(Packet * p);
		
		double getValue();

		bool isFull();

		void setEmptyBias(double bias);

		bool isEmpty();

		void setFullBias(double bias);
		
	private:
		char groupid;
		char boardid;
		PacketServer * ps;
		
		double currentValue;
		bool full;
		bool empty;
};

#endif // BATTERYBOARDPACKETHANDLER_CPP
