// Class automatically generated by Dev-C++ New Class wizard

#include "batterypacket.h" // class's header file

// class constructor
BatteryPacket::BatteryPacket() : GroupPacket(BATTERYSENSOR_ID)
{
}

// class destructor
BatteryPacket::~BatteryPacket()
{
	// insert your code here
}

void BatteryPacket::senseBattery(){
	this->setCommand(CMD_BATTERY_VALUE);
}

bool BatteryPacket::isBatteryFull(){
	return this->getCommand() == CMD_FULL_BATTERY_ALARM;
}

void BatteryPacket::setBatteryEmptyThreshold(short value){
	this->setCommand(CMD_BATTERY_EMPTY_VALUE);
	this->addData(value);
}

bool BatteryPacket::isBatteryEmpty(){
	return this->getCommand() == CMD_BATTERY_EMPTY_ALARM;
}

short BatteryPacket::getBatteryValue(){
	return this->getShortData();
}
