// Class automatically generated by Dev-C++ New Class wizard

#include "BoardPacketHandler.h" // class's header file

// class constructor
BoardPacketHandler::BoardPacketHandler()
{
	// insert your code here
}
