// Class automatically generated by Dev-C++ New Class wizard

#ifndef DCMOTORPACKET_H
#define DCMOTORPACKET_H

#define DCMOTORPACKET_ID 0x01
#include "GroupPacket.h" // inheriting class's header file

/**
 * No description
 */
class DCMotorPacket : public GroupPacket
{
	public:
		// class constructor
		DCMotorPacket();
		// class destructor
		~DCMotorPacket();
};

#endif // DCMOTORPACKET_H
