// Class automatically generated by Dev-C++ New Class wizard

#include "floorsensorpacket.h" // class's header file

// class constructor
FloorSensorPacket::FloorSensorPacket() : DistanceSensorPacket()
{
}

// class destructor
FloorSensorPacket::~FloorSensorPacket()
{
	// insert your code here
}
