// Class automatically generated by Dev-C++ New Class wizard

#include "GroupPacket.h" // class's header file

// class constructor
GroupPacket::GroupPacket(char groupid)
{
	this->groupid = groupid;
	// insert your code here
}

// class destructor
GroupPacket::~GroupPacket()
{
	// insert your code here
}
