// Class automatically generated by Dev-C++ New Class wizard

#ifndef GROUPPACKET_H
#define GROUPPACKET_H

#include "BasePacket.h" // inheriting class's header file
#include <string>

#define BP_INIT 0x01
#define BP_RESET 0x02
#define BP_PING 0x03
#define BP_ERROR 0x04

/**
 * No description
 */
class GroupPacket : public BasePacket
{
	public:
		// class constructor
		GroupPacket(char groupid);
		// class destructor
		~GroupPacket();
	private:
		char groupid;
};

#endif // GROUPPACKET_H
