// Class automatically generated by Dev-C++ New Class wizard

#ifndef PACKETSERVER_H
#define PACKETSERVER_H

#include <queue>
#include <list>
#include <map>
#include "Packet.h"
#include "BoardPacketHandler.h"

/**
 * No description
 */
class PacketServer
{
	public:
		// class constructor
		PacketServer();
		// class destructor
		~PacketServer();
		
		void sendPacket(Packet * p);
	private:
		void sendAPacket(Packet * p);
		std::queue<Packet *> toSend;
		std::list<Packet *> waitingForResponse;
		std::map<char, std::map<char, BoardPacketHandler *> > handlers;
};

#endif // PACKETSERVER_H
