// Class automatically generated by Dev-C++ New Class wizard

#include "ServoBoardPacketHandler.h" // class's header file

// class constructor
ServoBoardPacketHandler::ServoBoardPacketHandler()
{
	// insert your code here
}

// class destructor
ServoBoardPacketHandler::~ServoBoardPacketHandler()
{
	// insert your code here
}

void ServoBoardPacketHandler::handlePacket(Packet * p){
}
