// Class automatically generated by Dev-C++ New Class wizard

#ifndef TRASHBINPACKET_H
#define TRASHBINPACKET_H

#include "BoardPacket.h" // inheriting class's header file

#define CMD_TRASHBIN_VALUE 0x40
#define CMD_FULL_TRASHBIN_ALARM 0x41
#define CMD_FULL_TRASHBIN_VALUE 0x42

/**
 * No description
 */
class TrashBinPacket : public BoardPacket
{
	public:
		// class constructor
		TrashBinPacket(char groupid, char boardid);
		// class destructor
		~TrashBinPacket();

		void senseTrashBin();
		bool isTrashBinFull();
		void setTrashBinFullThreshold(short value);
		
		short getTrashBinValue();
};

#endif // TRASHBINPACKET_H
