// Class automatically generated by Dev-C++ New Class wizard

#include "ultrasonicsensorpacket.h" // class's header file

// class constructor
UltrasonicSensorPacket::UltrasonicSensorPacket(char groupid, char boardid) : DistanceSensorPacket(groupid, boardid)
{
}

// class destructor
UltrasonicSensorPacket::~UltrasonicSensorPacket()
{
	// insert your code here
}

