// Class automatically generated by Dev-C++ New Class wizard

#ifndef BOARDPACKET_H
#define BOARDPACKET_H

#include <packets/GroupPacket.h> // inheriting class's header file

namespace packets {

/**
 * No description
 */
class BoardPacket : public packets::GroupPacket
{
	public:
		// class constructor
		BoardPacket(char groupid, char boardid);
		// class destructor
		~BoardPacket();
		void prepareToSend();
	protected:
		char boardid;
};

}

#endif // BOARDPACKET_H

