// Class automatically generated by Dev-C++ New Class wizard

#include <packets/FloorSensorPacket.h> // class's header file

namespace packets {

// class constructor
FloorSensorPacket::FloorSensorPacket(char groupid, char boardid) : packets::DistanceSensorPacket(groupid, boardid)
{
}

// class destructor
FloorSensorPacket::~FloorSensorPacket()
{
	// insert your code here
}

}
