// Class automatically generated by Dev-C++ New Class wizard

#ifndef ULTRASONICSENSORPACKET_H
#define ULTRASONICSENSORPACKET_H

#include <packets/DistanceSensorPacket.h> // inheriting class's header file

namespace packets {

/**
 * No description
 */
class UltrasonicSensorPacket : public packets::DistanceSensorPacket
{
	public:
		// class constructor
		UltrasonicSensorPacket(char groupid, char boardid);
		// class destructor
		~UltrasonicSensorPacket();

};

}
#endif // ULTRASONICSENSORPACKET_H
