// Class automatically generated by Dev-C++ New Class wizard

#include <packets/UltraSonicSensorPacket.h> // class's header file

namespace packets {

// class constructor
UltrasonicSensorPacket::UltrasonicSensorPacket(char groupid, char boardid) : packets::DistanceSensorPacket(groupid, boardid)
{
}

// class destructor
UltrasonicSensorPacket::~UltrasonicSensorPacket()
{
	// insert your code here
}

}
