#include "Garbage.h"

namespace utils {

 {


double Garbage::angleTo()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010BB begin
{
    return 0.0;
}
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010BB end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

double Garbage::distanceTo()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010BD begin
{
    return 0.0;
}
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010BD end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Rectangle Garbage::boundingBox()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010BF begin
{
}
// section -64--88-1-100--739dc8b6:125f59cdd61:-8000:00000000000010BF end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

Garbage::Garbage()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-101--47fc296c:125fbe9bb5c:-8000:00000000000010F0 begin
{
    return 0;
}
// section -64--88-1-101--47fc296c:125fbe9bb5c:-8000:00000000000010F0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace utils */
