// Class automatically generated by Dev-C++ New Class wizard

#ifndef BATTERYPACKET_H
#define BATTERYPACKET_H

#include <protocol/packets/BoardPacket.h> // inheriting class's header file

#define CMD_BATTERY_ENABLE 0x40
#define CMD_BATTERY_DISABLE 0x41
#define CMD_BATTERY_VALUE 0x42
#define CMD_FULL_BATTERY_ALARM 0x43
#define CMD_BATTERY_EMPTY_VALUE 0x44
#define CMD_BATTERY_EMPTY_ALARM 0x45
#define CMD_BATTERY_FULL_VALUE 0x46

namespace protocol {
namespace packets {

/**
 * No description
 */
class BatteryPacket : public protocol::packets::BoardPacket
{
	public:
		// class constructor
		BatteryPacket(char groupid, char boardid);
		// class destructor
		~BatteryPacket();

		void enable();
		void disable();
		void senseBattery();
		bool isBatteryFull();
		void setBatteryEmptyThreshold(short value);
		bool isBatteryEmpty();
		void setBatteryFullThreshold(short value);
		
		short getBatteryValue();
};

}
}


#endif // BATTERYPACKET_H
