// Class automatically generated by Dev-C++ New Class wizard

#ifndef DISTANCESENSORPACKET_H
#define DISTANCESENSORPACKET_H

#include <protocol/packets/BoardPacket.h> // inheriting class's header file

#define CMD_ON 0x40
#define CMD_OFF 0x41
#define CMD_SET_STATUS 0x42
#define CMD_GET_STATUS 0x43
#define CMD_GET_VALUE 0x44
#define CMD_GET_ONE_VALUE 0x45
#define CMD_ALARM_ON 0x46

namespace protocol {
namespace packets {

/**
 * No description
 */
class DistanceSensorPacket : public protocol::packets::BoardPacket
{
	public:
		// class constructor
		DistanceSensorPacket(char groupid, char boardid);
		// class destructor
		~DistanceSensorPacket();

		// Commands to be sent
		void on(char sensorId);
		void off(char sensorId);
		void setMask(char sensorMask);
		void getMask();
		void getValue(char sensorIds);
		void getOneValue(char sensorIds);
		void alarmOn(char data);
	
		// Get data from package
		short getSensorValue();
		short * getSensorValues();
		short getShotSensorValue();
		short * getShotSensorValues();
		
		
		void alarmCommand(char * data);
};

}
}


#endif // DISTANCESENSORPACKET_H
