// Class automatically generated by Dev-C++ New Class wizard

#include <protocol/handlers/DefaultBoardPacketHandler.h> // class's header file

namespace protocol {
namespace handlers {

// class constructor
DefaultBoardPacketHandler::DefaultBoardPacketHandler(PacketServer * ps, char groupid, char boardid)
{
	this->groupid = groupid;
	this->boardid = boardid;
	this->ps = ps;

}

// class destructor
DefaultBoardPacketHandler::~DefaultBoardPacketHandler()
{
	// insert your code here
}

void DefaultBoardPacketHandler::handlePacket(Packet * p){
//	protocol::Packet * bp = new protocol::Packet();

}

}
}

