#ifndef behaviours_BehavioursParameters_h
#define behaviours_BehavioursParameters_h

#include <map>
#include <stdio.h>
#include <iostream>
#include <string.h>

#define LINE_UP_THRESHOLD "LINE_UP_THRESHOLD"
#define LINE_DOWN_THRESHOLD "LINE_DOWN_THRESHOLD"
#define RANGE "RANGE"

#define THRESHOLD_OBSTACLE "THRESHOLD_OBSTACLE"
#define FRONT_THRESHOLD_OBSTACLE "FRONT_THRESHOLD_OBSTACLE"
#define SPEED_FACTOR "SPEED_FACTOR"

#define BOTTOM_SERVO_ANGLE "BOTTOM_SERVO_ANGLE"
#define COLLECT_TIME_STEP "COLLECT_TIME_STEP"
#define COLLECT_BASE_SPD "COLLECT_BASE_SPD"
#define COLLECT_WAIT_STEPS "COLLECT_WAIT_STEPS"
#define COLLECT_WAIT_STEPS_A_LAST "COLLECT_WAIT_STEPS_A_LAST"
#define COLLECT_WAIT_STEPS_LAST "COLLECT_WAIT_STEPS_LAST"
#define COLLECT_ANGLE_TOLE "COLLECT_ANGLE_TOLE"
#define DISTANCE_TOLE "DISTANCE_TOLE"
#define SHOVEL_ANGLE "SHOVEL_ANGLE"

#define FIND_LINE_ANGLE_TOLE "FIND_LINE_ANGLE_TOLE"
#define FIND_LINE_BASE_SPD "FIND_LINE_BASE_SPD"

#define FOCUS_GARBAGE_BASE_SPD "FOCUS_GARBAGE_BASE_SPD"
#define FOCUS_GARBAGE_MIN_SPD "FOCUS_GARBAGE_MIN_SPD"

#define GO_TO_BASE_ORIENTATION_TOLE "GO_TO_BASE_ORIENTATION_TOLE"
#define GO_TO_BASE_BASE_FIX_ORIENTATION_TOLE "GO_TO_BASE_BASE_FIX_ORIENTATION_TOLE"
#define GO_TO_BASE_BASE_X "GO_TO_BASE_BASE_X"
#define GO_TO_BASE_TOLE "GO_TO_BASE_TOLE"
#define GO_TO_BASE_BASE_POSITION "GO_TO_BASE_BASE_POSITION"
#define GO_TO_BASE_PASSAGE_BEGIN_X "GO_TO_BASE_PASSAGE_BEGIN_X"
#define GO_TO_BASE_PASSAGE_LINE_Z "GO_TO_BASE_PASSAGE_LINE_Z"
#define GO_TO_BASE_LINE_MARK_X "GO_TO_BASE_LINE_MARK_X"
#define GO_TO_BASE_LINE_ORIENTATION_CORRECTION "GO_TO_BASE_LINE_ORIENTATION_CORRECTION"
#define GO_TO_BASE_FROM_Z_LEFT "GO_TO_BASE_FROM_Z_LEFT"
#define GO_TO_BASE_X_CORRECTION_LINE "GO_TO_BASE_X_CORRECTION_LINE"
#define GO_TO_BASE_FROM_Z_RIGHT "GO_TO_BASE_FROM_Z_RIGHT"
#define GO_TO_BASE_EMPTY_BIAS "GO_TO_BASE_EMPTY_BIAS"
#define GO_TO_BASE_FULL_BIAS "GO_TO_BASE_FULL_BIAS"
#define GO_TO_BASE_LINE_X_POSITION_THRESHOLD "GO_TO_BASE_LINE_X_POSITION_THRESHOLD"

#define GO_TO_BASE_BASE_SPD "GO_TO_BASE_BASE_SPD"
#define GO_TO_BASE_SPD_FACTOR "GO_TO_BASE_SPD_FACTOR"

#define GO_TO_D_ORIENTATION_TOLE "GO_TO_D_ORIENTATION_TOLE"
#define BASE_X "BASE_X"
#define TOLE "TOLE"
#define BASE_POSITION "BASE_POSITION"
#define AFTER_ALIGN_ORIENTATION -1.59682 "AFTER_ALIGN_ORIENTATION -1.59682"
#define GO_TO_D_LINE_X_POSITION_THRESHOLD "GO_TO_D_LINE_X_POSITION_THRESHOLD"
#define PASSAGE_BEGIN_X "PASSAGE_BEGIN_X"
#define PASSAGE_LINE_Z "PASSAGE_LINE_Z"
#define LINE_MARK_X "LINE_MARK_X"
#define LINE_ORIENTATION_CORRECTION "LINE_ORIENTATION_CORRECTION"
#define FROM_Z_LEFT "FROM_Z_LEFT"
#define X_CORRECTION_LINE "X_CORRECTION_LINE"
#define FROM_Z_RIGHT "FROM_Z_RIGHT"

#define GO_TO_GARBAGE_ANGLE_TOLE "GO_TO_GARBAGE_ANGLE_TOLE"
#define GO_TO_GARBAGE_MAX_SPD "GO_TO_GARBAGE_MAX_SPD"
#define GO_TO_GARBAGE_MIN_SPD "GO_TO_GARBAGE_MIN_SPD"

#define POSITIONING_BASE_SPD "POSITIONING_BASE_SPD"
#define POSITION_ANGLE_TOLE "POSITION_ANGLE_TOLE"
#define POSITION_TURN_FACTOR "POSITION_TURN_FACTOR"
#define POSITION_TIME_STEP "POSITION_TIME_STEP"

#define MIDDLE_LINE_X "MIDDLE_LINE_X"

#define RECHARGE_TIME_STEP "RECHARGE_TIME_STEP"
#define RECHARGE_ORIENTATION_TOLE "RECHARGE_ORIENTATION_TOLE"
#define RECHARGE_BACKWARD_STEPS "RECHARGE_BACKWARD_STEPS"
#define RECHARGE_BACKWARD_SPD "RECHARGE_BACKWARD_SPD"
#define RECHARGE_FORWARD_SPD "RECHARGE_FORWARD_SPD"
#define RECHARGE_BASE_X "RECHARGE_BASE_X"
#define RECHARGE_BASE_Z "RECHARGE_BASE_Z"
#define RECHARGE_BASE_ANGLE "RECHARGE_BASE_ANGLE"
#define RECHARGE_BASE_SPD "RECHARGE_BASE_SPD"
#define RECHARGE_SPD_FACTOR "RECHARGE_SPD_FACTOR"
#define RECHARGE_E_PUCK_DIAMETER "RECHARGE_E_PUCK_DIAMETER"

#define REMOVE_ANGLE_TOLE "REMOVE_ANGLE_TOLE"
#define REMOVE_SPD "REMOVE_SPD"
#define REMOVE_STEP "REMOVE_STEP"
#define REMOVE_DESVSTD_ANGLE_THRESHOLD "REMOVE_DESVSTD_ANGLE_THRESHOLD"
#define REMOVE_DESVSTD_DIST_THRESHOLD "REMOVE_DESVSTD_DIST_THRESHOLD"
#define REMOVE_ANGLE_TO_ADD "REMOVE_ANGLE_TO_ADD"

#define UNLOAD_TIME_STEP "UNLOAD_TIME_STEP"
#define UNLOAD_ORIENTATION_TOLE "UNLOAD_ORIENTATION_TOLE"
#define UNLOAD_BACKWARD_STEPS "UNLOAD_BACKWARD_STEPS"
#define UNLOAD_BACKWARD_SPD "UNLOAD_BACKWARD_SPD"
#define UNLOAD_FORWARD_STEPS "UNLOAD_FORWARD_STEPS"
#define UNLOAD_FORWARD_SPD "UNLOAD_FORWARD_SPD"
#define UNLOAD_BASE_X "UNLOAD_BASE_X"
#define UNLOAD_BASE_Z "UNLOAD_BASE_Z"
#define UNLOAD_BASE_ANGLE "UNLOAD_BASE_ANGLE"
#define UNLOAD_WAIT_STEPS "UNLOAD_WAIT_STEPS"
#define UNLOAD_E_PUCK_DIAMETER "UNLOAD_E_PUCK_DIAMETER"
#define UNLOAD_BASE_SPD "UNLOAD_BASE_SPD"
#define UNLOAD_SPD_FACTOR "UNLOAD_SPD_FACTOR"

#define WANDER_SPD "WANDER_SPD"
#define WANDER_TURN_FACTOR "WANDER_TURN_FACTOR"
#define WANDER_STEPS_BASE "WANDER_STEPS_BASE"

#define GET_PARAM(param) behaviours::BehavioursParameters::getParameter(param)
//Comparator for map keys
struct ltstr
{
  bool operator()( char* s1, char* s2) const
  {
    return strcmp(s1, s2) < 0;
  }
};


namespace behaviours{
	class BehavioursParameters{
		
		public:
			~BehavioursParameters();
			
			
		public:
			static void setParameter(char * param,double val);
			static void Init(FILE * config);
			static double getParameter(char * param);
	};
}



#endif // behaviours_BehavioursParameters_h
